# Generated by Django 6.0.6 on 2026-07-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('capacity_kva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hybrid', models.BooleanField(default=True)),
                ('voltage', models.PositiveIntegerField()),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warranty', models.PositiveIntegerField(default=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('controller_type', models.CharField(choices=[('MPPT', 'MPPT'), ('PWM', 'PWM')], max_length=20)),
                ('current_rating', models.PositiveIntegerField()),
                ('voltage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('battery_type', models.CharField(choices=[('Lithium', 'Lithium'), ('Tubular', 'Tubular'), ('Gel', 'Gel'), ('AGM', 'AGM')], max_length=20)),
                ('voltage', models.PositiveIntegerField()),
                ('capacity_ah', models.PositiveIntegerField()),
                ('cycle_life', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('wattage', models.PositiveIntegerField()),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('warranty', models.PositiveIntegerField(default=25)),
                ('active', models.BooleanField(default=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.manufacturer')),
            ],
        ),
    ]
