# Generated by Django 6.0.6 on 2026-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturers/'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='support_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
