# Generated by Django 6.0.6 on 2026-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_manufacturer_country_manufacturer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Lighting', 'Lighting'), ('Cooling', 'Cooling'), ('Kitchen', 'Kitchen'), ('Entertainment', 'Entertainment'), ('Office', 'Office'), ('Industrial', 'Industrial'), ('Agriculture', 'Agriculture'), ('Medical', 'Medical'), ('Other', 'Other')], default='Other', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('default_wattage', models.PositiveIntegerField()),
                ('surge_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('default_hours', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('energy_efficient', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
