# Generated by Django 6.0.6 on 2026-06-30 11:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('backup_hours', models.PositiveIntegerField(default=8, help_text='Desired backup duration in hours.')),
                ('peak_sun_hours', models.DecimalField(decimal_places=2, default=Decimal('5.50'), help_text='Average peak sun hours.', max_digits=4)),
                ('system_voltage', models.PositiveIntegerField(choices=[(12, '12 Volts'), (24, '24 Volts'), (48, '48 Volts')], default=48)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Lighting', 'Lighting'), ('Cooling', 'Cooling'), ('Heating', 'Heating'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Entertainment', 'Entertainment'), ('Industrial', 'Industrial'), ('Other', 'Other')], default='Other', max_length=30)),
                ('appliance_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('power_rating', models.DecimalField(decimal_places=2, help_text='Running power in Watts.', max_digits=10)),
                ('surge_power', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting/Surge power in Watts.', max_digits=10)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('voltage', models.PositiveIntegerField(default=230, help_text='Operating voltage.')),
                ('power_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Power factor.', max_digits=3)),
                ('efficiency', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Appliance efficiency (%).', max_digits=5)),
                ('critical_load', models.BooleanField(default=False)),
                ('simultaneous', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='audits.assessment')),
            ],
            options={
                'verbose_name': 'Appliance',
                'verbose_name_plural': 'Appliances',
                'ordering': ['id'],
            },
        ),
    ]
