# Generated by Django 6.0.6 on 2026-07-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_assessment_completion_percentage_and_more'),
        ('equipment', '0003_appliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('wattage', models.PositiveIntegerField()),
                ('surge_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('daily_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.appliance')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audits.assessment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
