# Generated by Django 6.0.6 on 2026-07-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_assessmentitem'),
        ('equipment', '0003_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='library_appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_appliances', to='equipment.appliance'),
        ),
        migrations.DeleteModel(
            name='AssessmentItem',
        ),
    ]
