# Generated by Django 6.0.6 on 2026-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, help_text='Town, district or estate (e.g. Lekki Phase 1, GRA, Wuse II)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
